### ISSUE TITLE
Games on staging are sometimes running old code.

### ISSUE THREAD

**Issue by NiallEgan** [ocadotechnology/aimmo#770]
**Describe the bug**
@rdcruzCFL discovered a bug where the code did not update correctly when she tried to submit new code. 
The new code was:
```python
class Avatar(object):
   def handle_turn(self, world_map, avatar_state):
       from simulation.action import MoveAction
       import simulation.direction as direction
       import random

       print("new version")
       lost = random.randint(0,1)
       if lost == 1:
         print("Where am I?")
         print(avatar_state.location)

       next_direction = random.choice(direction.ALL_DIRECTIONS)
       return MoveAction(next_direction)

   def fruit(amount):
     if amount == 0:
       print("No apples today!")
     else:
       print("We have", amount, "apples")

        def vegetables(amount):
            if amount == 0:
                print("No apples today!")
            else:
                print("We have", amount, "apples")
```
It was in game 8. 

**To Reproduce**
We are currently unable to reproduce this; we need to conduct a thorough investigation on staging to find what happened. 

**Expected behavior**
The code should update correctly and all errors should be cleared. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4785252/44786300-98f81880-ab8b-11e8-9001-cb1817f2bae5.png)

**Comment by NiallEgan** [comment]
Here is what I think is happening:
- Looking at https://console.cloud.google.com/errors/CMKZ4ePam4e-wAE?service=gke_instances&time=P30D&project=decent-digit-629, this game (8) is unsuccessfully attempting to get code for player 13. This causes there to be no code update.
- I think the reason that it can't get the code for player 13 is because 13 is not the correct id.  There is an aimmo-8-worker-10 and aimmo-8-worker-12. This would suggest that player 10 or player 12 should be the correct url. 
- Overall, I think this is related to the issue of us having these weird player ids (e.g. 10, 12 instead of 1, 2). I think that if we fix that issue we should fix this. 

Also I saw the same same thing on James' screen when we were investigating an unrelated issue, so I don't think this is a one off.

**Comment by NiallEgan** [comment]
Actually I don't think the above comment is correct. I was able to replicate the bug with James, and the problem was that the page had been left open for a long time and the authentication cookie had expired, meaning that the code was not being POSTed successfully.  I have created a feature request at: https://github.com/ocadotechnology/aimmo/issues/785 to give the user some warning about this. 

IMO I think this issue should be closed because the backend was actually running the correct code the whole time and the issue is actually more of a UI one.

**Comment by OlafSzmidt** [comment]
Still doesn't explain the fact why was there a worker 10 and 12 but the endpoint was called at ID 13 :(

**Comment by NiallEgan** [comment]
Well the problem is that the log entry I was referring to above has been deleted so I can no longer verify that what I was saying was 100% correct. Also, I now suspect that those HTTP errors may actually be related to the server software we are using (I don't think we're using production ready server software in the containers) and not ids. Not too sure though

**Comment by NiallEgan** [comment]
Yeah I think that the thing is we can't replicate the issue with the logging in / out stuff. We can however replicate it without that.

**Comment by NiallEgan** [comment]
We're closing this for now as we believe we have identified the issue and have created a github issue to address it.
